In [4]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('spam.csv', encoding = 'latin1')

In [8]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
2878,ham,U still painting ur wall?,NaN,NaN,NaN
2113,ham,"Yeah, don't go to bed, I'll be back before mid...",NaN,NaN,NaN
1152,ham,Ok i go change also...,NaN,NaN,NaN
1556,ham,Good sleep is about rhythm. The person has to ...,NaN,NaN,NaN
798,ham,Ok i msg u b4 i leave my house.,NaN,NaN,NaN

In [9]:
df.shape

(5572, 5)

In [ ]:
# 1. Data Cleaning
# 2. EDA
# 3. Text Preprocessing
# 4. Model Building
# 5. Evaluation
# 6. Improvement
# 7. Website
# 8. Deploy

## 1. Data Cleaning

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [12]:
# drop last 3 columns
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace=True)

In [13]:
df.sample(5)

        v1                                                 v2
857    ham  Hai ana tomarrow am coming on morning.  &lt;DE...
2869  spam  YOUR CHANCE TO BE ON A REALITY FANTASY SHOW ca...
3218   ham  Me too baby! I promise to treat you well! I be...
2384   ham                             Sorry, I'll call later
4183   ham  I just really need shit before tomorrow and I ...

In [15]:
# renaming the columns
df.rename(columns={'v1' : 'Target' , 'v2' : 'Text'},inplace=True)
df.sample(5)

     Target                                               Text
5105    ham  I wnt to buy a BMW car urgently..its vry urgen...
156     ham                        I'm leaving my house now...
1517   spam  Our brand new mobile music service is now live...
1229    ham                    Jus ans me lar. U'll noe later.
3135    ham  Can you let me know details of fri when u find...

In [17]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [18]:
df['Target'] = encoder.fit_transform(df['Target'])

In [19]:
df.head()

   Target                                               Text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [20]:
# missing values ?
df.isnull().sum()

Target    0
Text      0
dtype: int64

In [21]:
# check for duplicate values
df.duplicated().sum()

np.int64(403)

In [23]:
# remove Duplicate Values
df = df.drop_duplicates(keep = 'first')

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.shape

(5169, 2)

## 2. EDA